apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  KC_DB: <dbmam>
  KC_DB_URL: jdbc:postgresql://postgres.database.svc.cluster.local:5432/appdb
  KC_DB_USERNAME: <username>
  KC_DB_PASSWORD: <password>
  KEYCLOAK_ADMIN: <adminusername|admin>
  KEYCLOAK_ADMIN_PASSWORD: "<admin password>"
