apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-data
  namespace: nifi
  labels:
    app: nifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
