apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: nifi
  labels:
    app: nifi

spec:
  selector:
    app: nifi
    component: dataflow

  ports:
    - name: http
      port: 80
      targetPort: 8080

    - name: https
      port: 443
      targetPort: 8443
