apiVersion: v1
kind: ConfigMap
metadata:
  name: openwebui-config
  namespace: ai
data:
  DOMAIN_NAME: "ai.z-script.io"

  # Keycloak
  KEYCLOAK_REALM: "iot"
  KEYCLOAK_BASE_URL: "http://keycloak.keycloak.svc.cluster.local:8080"

  # OpenWebUI
  WEBUI_NAME: "Z-Script AI"
