apiVersion: v1
kind: Secret
metadata:
  name: openwebui-secret
  namespace: ai
type: Opaque
stringData:
  OAUTH_CLIENT_ID: "openwebui"
  OAUTH_CLIENT_SECRET: "<keycloak secret>"

  # Optional secret key for sessions
  WEBUI_SECRET_KEY: "<id_for_user_ession>"

  OLLAMA_BASE_URL: "http://<ollamIPaddress>:11434"
  # Optional admin
  DEFAULT_USER_EMAIL: "admin@z-script.io"
  DEFAULT_USER_PASSWORD: "<not sure use case>"
  OLLAMA_BASE_URLS: "http://<ollamIPaddress>:11434"
