apiVersion: batch/v1
kind: Job
metadata:
  name: nextcloud-postgres-init
  namespace: nextcloud
  labels:
    app: nextcloud-postgres-init

spec:
  backoffLimit: 1

  selector:
    matchLabels:
      job-name: nextcloud-postgres-init

  template:
    metadata:
      labels:
        job-name: nextcloud-postgres-init

    spec:
      restartPolicy: Never

      containers:
        - name: postgres-init
          image: postgres:16

          env:
            - name: PGHOST
              value: postgres.database.svc.cluster.local

            - name: PGPORT
              value: "5432"
              
            - name: PGDATABASE
              value: appdb

            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: POSTGRES_USER

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: POSTGRES_PASSWORD

          command:
            - /bin/bash
            - -c
            - |
              set -e

              echo "Checking database..."
              psql -U "$PGUSER" -d "$PGDATABASE" -c "
               CREATE DATABASE nextcloud
               WITH OWNER appuser
               ENCODING 'UTF8'
               TEMPLATE template0
              " || true

              echo "Nextcloud DB ensured"
