apiVersion: apps/v1
kind: Deployment

metadata:
  name: nextcloud
  namespace: nextcloud

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nextcloud

  template:
    metadata:
      labels:
        app: nextcloud

    spec:
      containers:
        - name: nextcloud
          image: nextcloud:30-apache

          ports:
            - containerPort: 80

          env:
            # ===== DATABASE 
            - name: POSTGRES_HOST
              value: "postgres.database.svc.cluster.local"

            - name: POSTGRES_DB
              value: "nextcloud"

            - name: POSTGRES_USER
              value: "appuser"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: postgres-password

            - name: POSTGRES_PORT
              value: "5432"

            # ===== NEXTCLOUD ADMIN AUTO CREATE =====
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: nextcloud-admin-user

            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: nextcloud-admin-password

            # ===== DOMAIN =====
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "share.z-script.io"

            - name: OVERWRITEHOST
              value: "share.z-script.io"

            - name: OVERWRITEPROTOCOL
              value: "http"

            # ===== OIDC =====
            - name: OIDC_PROVIDER_URL
              value: "http://keycloak.keycloak.svc.cluster.local/realms/main"

            - name: OIDC_CLIENT_ID
              value: "nextcloud"

            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: client-secret

          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html

            - name: bootstrap
              mountPath: /bootstrap

          command:
            - /bin/bash
            - -c
            - |
              /entrypoint.sh apache2-foreground &
              (
                sleep 60
                bash /bootstrap/bootstrap.sh
              ) &
              wait

      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data

        - name: bootstrap
          configMap:
            name: nextcloud-bootstrap
            defaultMode: 0755
