apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 06-ingress.yaml
  - 03-pvc.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - 02-bootsrap-config-map.yaml
  - ingress-configmap.yaml
  - init-db.yaml
