cat secret-nextcloud.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  POSTGRES_USER: "<postgre admin user>"
  POSTGRES_PASSWORD: "<postgre admin password to create init database>"
  postgres-password: "<postgre admin password to create init database>"
  nextcloud-admin-user: "admin"
  nextcloud-admin-password: "copy from keycloak| no needm because keycloak will be there"
  client-secret: "<copy from keycloak>"
