apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  postgres-password: "<change>"
  nextcloud-admin-user: "admin"
  nextcloud-admin-password: "<changeToo>"
