apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
  labels:
    app: postgres
    role: database
spec:
  type: ClusterIP
  selector:
    app: postgres
    role: database
  ports:
    - port: 5432
      targetPort: 5432
