apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-data-pvc
  namespace: nifi
  labels:
    app: nifi
    tier: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
