apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: nifi
  labels:
    app: nifi
    tier: data
spec:
  selector:
    app: nifi
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
