apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-config-map
  namespace: nifi

data:
  nifi.properties.tpl: |
    nifi.web.https.port=8443
    nifi.web.proxy.host=${NIFI_WEB_PROXY_HOST}

    nifi.security.user.oidc.discovery.url=${OIDC_DISCOVERY_URL}
    nifi.security.user.oidc.client.id=${OIDC_CLIENT_ID}
    nifi.security.user.oidc.client.secret=${OIDC_CLIENT_SECRET}

    nifi.security.user.oidc.claim.identifying.user=preferred_username
    nifi.security.user.oidc.additional.scopes=openid,email,profile
    nifi.sensitive.props.key=${PROPS_KEY}
    nifi.security.keystorePasswd=${KEYSTORE_PASSWORD}
    nifi.security.keyPasswd=${KEY_PASSWORD}
    nifi.security.truststorePasswd=${TRUSTSTORE_PASSWORD}
