apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-data
  namespace: nifi
  labels:
    app: nifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
