apiVersion: v1
kind: Secret
metadata:
  name: nifi-oidc-secret
  namespace: nifi
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: "<init from keycloak>"
  TRUSTSTORE_PASSWORD: "<init from nifi.properties>"
  KEYSTORE_PASSWORD: "<init from nifi.properties>"
  KEY_PASSWORD: "<init from nifi.properties>"
  PROPS_KEY: "<init from nifi.properties>"
